#!/usr/bin/env bash
# Run every nitomic program under clonim and compare its output with the
# output the same program produced on the JVM against Datomic Pro
# (test/expected/, regenerated by script/reference.sh).
#
#   CLONIM=/path/to/clonim test/run.sh      # default: clonim on PATH
set -u
cd "$(dirname "$0")/.."
clonim="${CLONIM:-clonim}"
programs=(examples/seattle/getting_started.clj test/features.clj test/native.clj test/storage.clj test/transactor.clj)
fail=0
for f in "${programs[@]}"; do
  name=$(basename "$f" .clj)
  expected="test/expected/$name.out"
  got=$(mktemp)
  "$clonim" run "$f" --source-path src > "$got" 2>&1
  if diff -u "$expected" "$got" > "$got.diff"; then
    echo "ok   $name"
  else
    echo "FAIL $name"
    head -40 "$got.diff"
    fail=1
  fi
  rm -f "$got" "$got.diff"
done
exit $fail
